### ISSUE TITLE
New features: hightlight, asciiMath and checklist

### ISSUE THREAD

**Issue by mlopezgva** [classeur/classeur#162]
Hello!

I've been wandering through many MD editors and parsers. I think that, while keeping the "core"  is vital (tell me about "so many standards"), there are many features out there that are very interesting (like GitHub extensions) and others that could be easier to use (like Math) than using LaTeX (binary can be easier... :D) It would be good to see some of them added to the markdown "core".

So, here are some ideas to improve Classeur, easiest first:
- [ ] highlight text using `==`  ==text== becomes `<span style='background-color:yellow'>text</span>`
- [ ] Checklists (GitHub extension, and **this  list** is a checklist, just to prove how does it looks ;))
- [ ] CSV to Table, perhaps through fenced code (```csv to trigger the conversion)
- [ ] a Table of Contents. That's tricky, but I've seen some implementations using the `[TOC]` token
- [ ] **UML** diagrams using [PlantUML](http://plantuml.com) (consistent syntax for 8 UML diagrams, highly configurable, implemented in **_StackEdit**_ using ```uml as trigger)
- [ ] [AsciiMath](http://asciimath.org), because it's easy to write (markdown's main goal, IMHO), yet powerful
### Simplest additions

Checklists and highlight are trivial, and feels like MarkDown. The logic for the ToC is already there, it would be just a question about what would trigger it.
### CSV to Table

CSV has been around for decades, and it's still in use, and it would be a good addition to have a parser that converts a CSV to table, there are many situations where this can be interesting, since office suites don't convert tables to MarkDown tables, but they can convert tables to CSV, and it's still easy to read (and write!).
I have a parser (taken from github issues page) from csv to MD table in **_StackEdit**_, using fenced code and using `csv` (and `tsv`) as keyword.
### PlantUML

PlantUML is the best text2diagram software I've seen, even if it's written in Java :p 
It has a good documentation (could be better, but it's well structured and very complete), and is has many features: color customization, some asciiDoc like capabilities, it renders SVG, PNG and even ASCII art!

I have it in StackEdit (taken from GitHub issues page) using fenced code and the keyword `uml`. That's consistent, since the text to create a diagram is a code of some sort.

It can produce:
- Sequence diagram,
- Use Case diagram,
- Class diagram,
- Object diagram,
- Activity diagram,
- Component diagram,
- State diagram,
- Deployment diagram,
- Wireframe graphical interface

Very complete OSS.
### Math and ASCII Math

Using LaTeX for anything is always a PITA... that's why MarkDown exists, in fact. :) so, mathematical expressions should also be easier to type. And looking around, from MathJax thanks to StakEdit, I found AsciiMath.

**MathJax** is good, but **AsciiMath** is even easier and covers many common scenarios. I would suggest to allow both in the Options, specially since the MathJax library contains the AsciiMath parser.

Just to make a point, see the difference between TeX and asciiMath with these examples. I must say I could write the quadratic formula without taking a look at the syntax. It's really **easy**:
- _Cauchy-Schwarz Inequality_, the difference is breathtaking:
  - TeX:
    `\[ \left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right) \]`
  - AsciiMath:

```
    (sum_(k=1)^n a_kb_k)^2 <=
    (sum_(k=1)^n a_k^2)
    (sum_(k=1)^n b_k^2)`
```

  The most important about this one, is that I didn't peek  at the syntax... It's just "natural". I'm very impressed.
![captura de pantalla de 2016-07-14 17 01 13](https://cloud.githubusercontent.com/assets/996070/16855241/d0114eae-49ea-11e6-8336-41c1a189cc66.png)
- Lorenz:
  - TeX:
    `\dot{x} = \sigma(y-x) \\ \dot{y} = \rho x - y - xz \\ \dot{z} = -\beta z + xy`
  - AsciiMath:
    `dotx = sigma(y-x)`
    `\doty = rho x-y - xz`
    `\dotz = -beta z + xy`
- Probability:
  - TeX:
    `\[P(E)   = {n \choose k} p^k (1-p)^{ n-k } \]`
  - AsciiMath:
    `P(E) = ((n),(k)) p^k (1-p)^(n-k)`

![captura de pantalla de 2016-07-14 17 18 59](https://cloud.githubusercontent.com/assets/996070/16855268/fa423bb6-49ea-11e6-9642-b78d58a108bf.png)
- And, of course, the quadratic formula:
  - TeX:
    `-b \pm \sqrt{b^2 - 4ac} \over 2a`
  - AsciiMath
    `x=-b+- sqrt(b^2-4ac)/(2a)`

![captura de pantalla de 2016-07-14 17 18 33](https://cloud.githubusercontent.com/assets/996070/16855277/02ed5e62-49eb-11e6-887b-61325ceb70b3.png)

**Comment by orschiro** [comment]
Thank you @mlopezgva!

I am marking this as an enhancement request for later evaluation. :+1: 

~Robert

**Comment by mlopezgva** [comment]
Some more examples comparing the same formulas in Markdown Plus help:

| Núm. | LaTeX | length | ASCII Math | length |
| --: | --- | --: | --- | --: |
| 1 | `\dfrac{ \tfrac{1}{2}[1-(\tfrac{1}{2})^n] }{ 1-\tfrac{1}{2} } = s_n` | 66 | `(1/2[1-(1/2)^n])/(1-(1/2))=8_n` | **30** |
| 2 | `\oint_C x^3\, dx + 4y^2\, dy` | 28 | `oint_Cx^3 dx+4y^2 dy` | 21 |
| 3 | `2 = \left( \frac{\left(3-x\right) \times 2}{3-x} \right)` | 57 | `2=(((3-x)xx2)/(3-x))` | **20** |
| 4 | `\sum_{m=1}^\infty\sum_{n=1}^\infty\frac{m^2\,n} {3^m\left(m\,3^n+n\,3^m\right)}` | 80 | `sum_(m=1)^oosum_(n=1)^oo(m^2 n)/(3^m(m3^n+n3^m)` | **48** |

And the last one is so big (169 characters), I must put it as a code block...

```
phi_n(\kappa) =
 \frac{1}{4\pi^2\kappa^2} \int_0^\infty
 \frac{\sin(\kappa R)}{\kappa R}
 \frac{\partial}{\partial R}
 \left[R^2\frac{\partial D_n(R)}{\partial R}\right]\,dR
```

And, ASCIImath version:

```
phi_n(kappa) = 1/(4pi^2 kappa^2)
 int_0^oo (sin(kappa R))/(kappa R)
 del/(del R)
[R^2 (del D_n (R))/(del R)] del R
```

Its not so long (112 characters, including spaces, I could've put it in a oneliner:

`phi_n(kappa) = 1/(4pi^2 kappa^2)  int_0^oo (sin(kappa R))/(kappa R)  del/(del R) [R^2 (del D_n (R))/(del R)] del R`

See the difference? And there's another one: I had only peeked at the docs to see he "name" of the 'oint'. **Everything else** I was able to type without help, it's "natural" (something LaTeX is definetly not ;)).

So, please, consider ASCIImath as an alterane way to write math in markdown.

**Comment by orschiro** [comment]
Dear @mlopezgva,

Thank you very much for your insightful examples!

I do see why you want to have support for ASCIImath. 

I encourage @benweet to take a closer look at it. 

Warmly,

-Robert

**Comment by benweet** [comment]
@mlopezgva sorry I was confused with https://github.com/benweet/stackedit/issues/242.

Can you split this ticket into multiple enhancement requests?
Thank you in advance.
